source 'https://rubygems.org'

ruby '~> 3.2'

gem 'aws-sdk-dynamodb', '~> 1.95'
gem 'aws-sdk-s3', '~> 1.0'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22'
  gem 'simplecov-console', '~> 0.9'
end

